### This file contains sample REST Api requests.

### Get active asset symbols.
GET http://localhost:5000/symbols

### Request a single asset symbol.
POST http://localhost:5000/request
Content-Type: application/json

[
    "AAPL"
]

### Request for multiple asset symbols.
POST http://localhost:5000/request
Content-Type: application/json

[
    "AAPL",
    "GOOGL"
]

### Empty list.
POST http://localhost:5000/request
Content-Type: application/json

[
]

### Invalid request format.
POST http://localhost:5000/request
Content-Type: application/json

{
    "name": "AAPL"
}

### Requesting an object to be added.
POST http://localhost:5000/request
Content-Type: application/json

[
    "GOOGL",
    {"name": "AAPL"}
]