### This file contains sample RESTApi requests.

### Get active tickers.
GET http://localhost:5000/tickers

### Request a single asset.
POST http://localhost:5000/request
Content-Type: application/json

[
    "AAPL"
]

### Request multiple tickers.
POST http://localhost:5000/request
Content-Type: application/json

[
    "AAPL",
    "GOOGL"
]

### Empty asset list.
POST http://localhost:5000/request
Content-Type: application/json

[
]

### Invalid request format.
POST http://localhost:5000/request
Content-Type: application/json

{
    "name": "AAPL"
}

### Requesting an object to be added.
POST http://localhost:5000/request
Content-Type: application/json

[
    "GOOGL",
    {"name": "AAPL"}
]