### This file contains sample REST Api requests.

### Get active asset symbols.
GET http://localhost:61000/symbols

### Request a single asset symbol.
POST http://localhost:61000/append
Content-Type: application/json

[
    "GOOGL"
]

### Request for multiple asset symbols.
POST http://localhost:61000/append
Content-Type: application/json

[
    "AAPL",
    "GOOGL"
]

### Empty list.
POST http://localhost:61000/append
Content-Type: application/json

[
]

### Request should come as an array.
POST http://localhost:61000/append
Content-Type: application/json

{
    "name": "AAPL"
}

### Requesting an object to be added.
POST http://localhost:61000/append
Content-Type: application/json

[
    "GOOGL",
    {"name": "AAPL"}
]

### Request for asset symbol price data.
GET http://localhost:61000/data?symbol=GOOGL&start_date=2024-10-20&end_date=2024-11-01

### Request for asset symbol price data.
GET http://localhost:61000/data?symbol=AAPL&start_date=2024-10-20&end_date=2024-11-01

### Request should include symbol, start_date and end_date
GET http://localhost:61000/data?symbol=AAPL&end_date=2024-11-04

### Request should include symbol, start_date and end_date
GET http://localhost:61000/data?symbol=GOOGL&start_date=2024-11-01