version: '3.8'

services:
  fintel-api-service:
    container_name: fintel-api-service
    build:
      context: ./api
    environment:
      - SERVICE_PORT=61000
    ports:
      - "61000:61000"
    volumes:
      - fintel-service-data:/home/fintel:rw
    depends_on:
      - fintel-database

  fintel-database:
    container_name: fintel-database
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: fintel-db
    secrets:
      - db_user
      - db_password
    volumes:
      - fintel-database-data:/var/lib/postgresql/data:rw

secrets:
  db_user:
    file: ./api/secrets/db_user
  db_password:
    file: ./api/secrets/db_password

volumes:
  fintel-service-data:
  fintel-database-data: