version: '3.8'

services:
  fintel-api-service:
    container_name: fintel-api-service
    build:
      context: ./
    volumes:
      - fintel-service-data:/app/data:rw
    environment:
      - SERVICE_PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - fintel-database

  fintel-database:
    container_name: fintel-database
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: fintel-db
    secrets:
      - db_user
      - db_password
    volumes:
      - fintel-database-data:/var/lib/postgresql/data:rw
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro

secrets:
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password

volumes:
  fintel-service-data:
  fintel-database-data: