#!/bin/sh

# Run this if you're using a posix compliant system.

if [ ! command -v python > /dev/null 2>&1 ]; then
    echo "Please install python in your system."
    exit -1
fi
if [ ! command -v pytest > /dev/null 2>&1 ]; then
    echo "Please install pytest in your system."
    exit -1
fi
if [ ! command -v flake8 > /dev/null 2>&1 ]; then
    echo "Please install flake8 in your system."
    exit -1
fi

# The directory where this script exists.
script_dir="$(dirname "$(readlink -f "$0")")"

# Check if the first argument is "test"
if [ "$1" = "test" ]; then
    # Check syntax of scripts.
    flake8 --exclude $script_dir/venv --ignore=E252,E501,W292,E302,\
        E231,E261,E302,E305,E502,E226,E402,E225,E227,E125,E128,\
        E225,E122,E131,E127,E124 $script_dir
    # Run the tests
    pytest -s $script_dir
else
    # Default behavior: Run the application
    python $script_dir/app.py
fi