#!/bin/sh

# Run this if you're using a posix compliant system.

if [ ! command -v python > /dev/null 2>&1 ]; then
    echo "Please install python in your system."
    exit -1
fi
if [ ! command -v pytest > /dev/null 2>&1 ]; then
    echo "Please install pytest in your system."
    exit -1
fi
if [ ! command -v flake8 > /dev/null 2>&1 ]; then
    echo "Please install flake8 in your system."
    exit -1
fi
if [ ! command -v gunicorn > /dev/null 2>&1 ]; then
    echo "Please install gunicorn in your system."
    exit -1
fi

# The directory where this script exists.
script_dir="$(dirname "$(readlink -f "$0")")"
# Change working directory to script_dir.
cd $script_dir

# Check if the first argument is "test"
if [ "$1" = "test" ]; then
    # Check syntax of scripts.
    flake8 --exclude ./venv --ignore=E252,E501,W292,E302,\
        E231,E261,E302,E305,E502,E226,E402,E225,E227,E125,E128,\
        E225,E122,E131,E127,E124
    # Run the tests
    pytest -s
else
    # Default behavior: Run the application
    gunicorn -w 4 -b 0.0.0.0:61000 'app:setup_app()'
fi