name: API Tests

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/api-tests.yaml"
      - "api/**"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/api-tests.yaml"
      - "api/**"

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run pytest
      run: pytest -s api