name: API

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/api.yaml"
      - "api/**"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/api.yaml"
      - "api/**"

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check syntax
      working-directory: api
      run: flake8 --exclude venv --ignore=E252,E501,W292,E302,E231,E261,E302,E305,E502,E226,E402,E225,E227,E125,E128,E225

    - name: Run pytest
      working-directory: api
      run: pytest -s