# This workflow builds all components of Fintel
name: build

on:
  push:
    branches:
      - "*"
    paths:
      - ".github/workflows/build.yaml"
      - "api/utils/**.py"
      - "api/.dockerignore"
      - "api/app.py"
      - "api/Dockerfile"
      - "api/requirements.txt"
      - "api/run"
      - "dashboard/pubspec.*"
      - "dashboard/web/**"
      - "dashboard/lib/**.dart"
  pull_request:
    branches:
      - "*"
    paths:
      - ".github/workflows/build.yaml"
      - "api/utils/**.py"
      - "api/.dockerignore"
      - "api/app.py"
      - "api/Dockerfile"
      - "api/requirements.txt"
      - "api/run"
      - "dashboard/pubspec.*"
      - "dashboard/web/**"
      - "dashboard/lib/**.dart"

jobs:
  build-api-service-image:
    runs-on:
      - self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build docker image
      working-directory: api
      run: |
        docker build -t aldhinn/fintel:api-service .

  build-web:
    runs-on:
      - self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Flutter packages
      working-directory: dashboard
      run: flutter pub get

    - name: Build web version
      working-directory: dashboard
      run: flutter build web --release